/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const ConsultancyForm = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'requirementMessage' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : Time,
  'phoneNumber' : IDL.Text,
  'location' : IDL.Text,
});
export const PartnerRegistration = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'businessDetails' : IDL.Text,
  'timestamp' : Time,
  'companyName' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'getAllConsultancyForms' : IDL.Func(
      [],
      [IDL.Vec(ConsultancyForm)],
      ['query'],
    ),
  'getAllOfferings' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllPartnerRegistrations' : IDL.Func(
      [],
      [IDL.Vec(PartnerRegistration)],
      ['query'],
    ),
  'getAllSolutions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getConsultancyFormById' : IDL.Func([IDL.Nat], [ConsultancyForm], ['query']),
  'getPartnerRegistrationById' : IDL.Func(
      [IDL.Nat],
      [PartnerRegistration],
      ['query'],
    ),
  'submitConsultancyForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitPartnerRegistration' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateConsultancyStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updatePartnerStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const ConsultancyForm = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'requirementMessage' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : Time,
    'phoneNumber' : IDL.Text,
    'location' : IDL.Text,
  });
  const PartnerRegistration = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'businessDetails' : IDL.Text,
    'timestamp' : Time,
    'companyName' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'getAllConsultancyForms' : IDL.Func(
        [],
        [IDL.Vec(ConsultancyForm)],
        ['query'],
      ),
    'getAllOfferings' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllPartnerRegistrations' : IDL.Func(
        [],
        [IDL.Vec(PartnerRegistration)],
        ['query'],
      ),
    'getAllSolutions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getConsultancyFormById' : IDL.Func(
        [IDL.Nat],
        [ConsultancyForm],
        ['query'],
      ),
    'getPartnerRegistrationById' : IDL.Func(
        [IDL.Nat],
        [PartnerRegistration],
        ['query'],
      ),
    'submitConsultancyForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitPartnerRegistration' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateConsultancyStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updatePartnerStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };