/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const AmcEnquiry = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'clientName' : IDL.Text,
  'email' : IDL.Text,
  'systemDetails' : IDL.Text,
  'timestamp' : Time,
  'phoneNumber' : IDL.Text,
  'location' : IDL.Text,
});
export const ConsultancyForm = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'requirementMessage' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : Time,
  'phoneNumber' : IDL.Text,
  'location' : IDL.Text,
});
export const PartnerRegistration = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'businessDetails' : IDL.Text,
  'timestamp' : Time,
  'companyName' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'location' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminGetAllAmcEnquiries' : IDL.Func([], [IDL.Vec(AmcEnquiry)], ['query']),
  'adminGetAllConsultancyForms' : IDL.Func(
      [],
      [IDL.Vec(ConsultancyForm)],
      ['query'],
    ),
  'adminGetAllPartnerRegistrations' : IDL.Func(
      [],
      [IDL.Vec(PartnerRegistration)],
      ['query'],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllOfferings' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllSolutions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAmcEnquiryById' : IDL.Func([IDL.Nat], [AmcEnquiry], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConsultancyFormById' : IDL.Func([IDL.Nat], [ConsultancyForm], ['query']),
  'getPartnerRegistrationById' : IDL.Func(
      [IDL.Nat],
      [PartnerRegistration],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitAmcEnquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitConsultancyForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitPartnerRegistration' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateAmcEnquiryStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateConsultancyStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updatePartnerStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const AmcEnquiry = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'clientName' : IDL.Text,
    'email' : IDL.Text,
    'systemDetails' : IDL.Text,
    'timestamp' : Time,
    'phoneNumber' : IDL.Text,
    'location' : IDL.Text,
  });
  const ConsultancyForm = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'requirementMessage' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : Time,
    'phoneNumber' : IDL.Text,
    'location' : IDL.Text,
  });
  const PartnerRegistration = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'businessDetails' : IDL.Text,
    'timestamp' : Time,
    'companyName' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'location' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminGetAllAmcEnquiries' : IDL.Func([], [IDL.Vec(AmcEnquiry)], ['query']),
    'adminGetAllConsultancyForms' : IDL.Func(
        [],
        [IDL.Vec(ConsultancyForm)],
        ['query'],
      ),
    'adminGetAllPartnerRegistrations' : IDL.Func(
        [],
        [IDL.Vec(PartnerRegistration)],
        ['query'],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllOfferings' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllSolutions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAmcEnquiryById' : IDL.Func([IDL.Nat], [AmcEnquiry], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConsultancyFormById' : IDL.Func(
        [IDL.Nat],
        [ConsultancyForm],
        ['query'],
      ),
    'getPartnerRegistrationById' : IDL.Func(
        [IDL.Nat],
        [PartnerRegistration],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitAmcEnquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitConsultancyForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitPartnerRegistration' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateAmcEnquiryStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateConsultancyStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updatePartnerStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };