/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ConsultancyForm {
  'id' : bigint,
  'status' : string,
  'name' : string,
  'requirementMessage' : string,
  'email' : string,
  'timestamp' : Time,
  'phoneNumber' : string,
  'location' : string,
}
export interface PartnerRegistration {
  'id' : bigint,
  'status' : string,
  'name' : string,
  'email' : string,
  'businessDetails' : string,
  'timestamp' : Time,
  'companyName' : string,
  'phoneNumber' : string,
  'location' : string,
}
export type Time = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'getAllConsultancyForms' : ActorMethod<[], Array<ConsultancyForm>>,
  'getAllOfferings' : ActorMethod<[], Array<string>>,
  'getAllPartnerRegistrations' : ActorMethod<[], Array<PartnerRegistration>>,
  'getAllSolutions' : ActorMethod<[], Array<string>>,
  'getConsultancyFormById' : ActorMethod<[bigint], ConsultancyForm>,
  'getPartnerRegistrationById' : ActorMethod<[bigint], PartnerRegistration>,
  'submitConsultancyForm' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'submitPartnerRegistration' : ActorMethod<
    [string, string, string, string, string, string],
    bigint
  >,
  'updateConsultancyStatus' : ActorMethod<[bigint, string], undefined>,
  'updatePartnerStatus' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];